# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
    # Path to main.go file or main package.
    # Default is `.`.
    main: ./cmd/goone/main.go
